### ISSUE TITLE
Can it be used in android?

### ISSUE THREAD

**Issue by kevin100702** [HavenDV/H.OxyPlot#7]
### Describe the bug

Thank you for porting OxyPlot to UNO!
I've used this great control on UWP, but when I run it with the android emulator the graph doesn't show up, am I doing something wrong?

XAML

`<oxy:PlotView Model="{x:Bind Model}"></oxy:PlotView>`

CS

```C#
public sealed partial class RealtimeLine2 : Page
    {
        public RealtimeLine2()
        {
            this.InitializeComponent();
            this.DataContext = this;
            Model = new PlotModel() { Title = "Simple Example", Subtitle = "using OxyPlot" };
            var series1 = new LineSeries { Title = "温度", MarkerType = MarkerType.Circle, InterpolationAlgorithm = InterpolationAlgorithms.CanonicalSpline };
            var series2 = new LineSeries { Title = "湿度", MarkerType = MarkerType.Circle, InterpolationAlgorithm = InterpolationAlgorithms.CanonicalSpline };
            var dateTimeAxis1 = new DateTimeAxis { Title = "Time"};
            Model.Axes.Add(dateTimeAxis1);
            Model.Series.Add(series1);
            Model.Series.Add(series2);

            Random rd = new Random();
            Task.Run(
                async () =>
                {
                    while (true)
                    {
                        series1.Points.Add(DateTimeAxis.CreateDataPoint(DateTime.Now, rd.Next(10, 30)));
                        series2.Points.Add(DateTimeAxis.CreateDataPoint(DateTime.Now, rd.Next(10, 30)));
                        //if (series1.Points.Count > 100)
                        //{
                        //    series1.Points.RemoveAt(0);
                        //    series2.Points.RemoveAt(0);
                        //}
                        Model.InvalidatePlot(true);
                        await Task.Delay(1000);
                    }
                });
        }

        private PlotModel _model;
        public PlotModel Model
        {
            get { return _model; }
            set { _model = value; }
        }
    }
```

### Steps to reproduce the bug

.net6 mobile

### Platform

Uno

### IDE

Visual Studio 2022

**Comment by HavenDV** [comment]
There was an issue here in the Uno test app where the graph was not showing up in some cases on first appearance. I fixed it, the fix will be available within 10-15 minutes.

**Comment by kevin100702** [comment]
Thank you for responding so quickly. I just updated to 0.9.30 and the graph still doesn't appear. I am using net6.0-android.

**Comment by HavenDV** [comment]
I will add an android test app and let you know the results

**Comment by HavenDV** [comment]
I tried it and here new problems appeared with the first display. But after changing the tabs, the graph appears.
![image](https://user-images.githubusercontent.com/3002068/189890089-82207207-7113-42a4-b885-13021c7d4f26.png)
